// <auto-generated />
using System;
using Efc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Efc.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240410121904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4");

            modelBuilder.Entity("Data.Entities.Drink", b =>
                {
                    b.Property<int>("DrinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AlcoholPrecentage")
                        .HasColumnType("REAL");

                    b.Property<int?>("DrinksMenuDrinkMenuId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeUmbrella")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("DrinkId");

                    b.HasIndex("DrinksMenuDrinkMenuId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("Data.Entities.DrinksMenu", b =>
                {
                    b.Property<int>("DrinkMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AvailableFrom")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContainsAlcohol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DrinkMenuId");

                    b.ToTable("DrinkMenus");
                });

            modelBuilder.Entity("Data.Entities.Drink", b =>
                {
                    b.HasOne("Data.Entities.DrinksMenu", null)
                        .WithMany("Drinks")
                        .HasForeignKey("DrinksMenuDrinkMenuId");
                });

            modelBuilder.Entity("Data.Entities.DrinksMenu", b =>
                {
                    b.Navigation("Drinks");
                });
#pragma warning restore 612, 618
        }
    }
}
